//         
    const category_list = [           
        'camp',           
        'sawmill',           
        'p&p',           
        'community',           
        'BCFS'           
    ]           
    //List of groups above           
    const region_categories = [   
        'coastalBC',           
        'CapitalRegionalDistrict',  
        'SaltspringIsland',  
        'NorthSaanich',  
        'Sidney',  
        'CentralSaanich',  
        'Saanich',  
        'Highlands',  
        'ViewRoyal',  
        'OakBay',  
        'Victoria',  
        'Esquimalt',  
        'Colwood',  
        'Langford',  
        'Metchosin',  
        'Sooke',  
        'CowichanValleyRegionalDistrict',  
        'ShawniganLake',  
        'MillBay/Malahat',  
        'CobbleHill',  
        'CowichanStation/Sahtlam/Glenora',  
        'CowichanBay',  
        'Duncan',  
        'NorthCowichan',  
        'LakeCowichan',  
        'Youbou/MeadeCreek',  
        'Ladysmith',  
        'NorthOyster/Diamond',  
        'RegionalDistrictofNanaimo',  
        'Nanaimo',  
        'Lantzville',  
        'Parksville',  
        'QualicumBeach',  
        'ComoxValleyRegionalDistrict',  
        'BaynesSound-Denman/HornbyIslands',  
        'Cumberland',  
        'Courtenay',  
        'Comox',  
        'Puntledge/BlackCreek',  
        'RegionalDistrictofAlberni-Clayoquot',  
        'PortAlberni',  
        'StrathconaRegionalDistrict',  
        'CampbellRiver',  
        'DiscoveryIslands/MainlandInlets',  
        'Cortes',  
        'OysterBay/ButtleLake',  
        'Kyuquot/Nootka-Sayward',  
        'GoldRiver',  
        'RegionalDistrictofMountWaddington',  
        'PortMcNeill',  
        'AlertBay',  
        'PortHardy',  
        'PortAlice',  
        'MetroVancouverRegionalDistrict',  
        'WhiteRock',  
        'Surrey',  
        'Langley',  
        'Delta',  
        'Richmond',  
        'Vancouver',  
        'Burnaby',  
        'NewWestminster',  
        'Coquitlam',  
        'PortMoody',  
        'Belcarra',  
        'Anmore',  
        'NorthVancouver',  
        'WestVancouver',  
        'PortCoquitlam',  
        'PittMeadows',  
        'MapleRidge',  
        'LionsBay',  
        'BowenIsland',  
        'SunshineCoastRegionalDistrict',  
        'WestHoweSound',  
        'Gibsons',  
        'Elphinstone',  
        'Sechelt',  
        'RobertsCreek',  
        'HalfmoonBay',  
        'Egmont/PenderHarbour',  
        'Squamish-LillooetRegionalDistrict',  
        'Squamish',  
        'Whistler',  
        'Pemberton',  
        'Lillooet',  
        'FraserValleyRegionalDistrict',  
        'Abbotsford',  
        'Mission',  
        'Chilliwack',  
        'HarrisonHotSprings',  
        'Kent',  
        'Hope',  
        'RegionalDistrictofOkanagan-Similkameen',  
        'Princeton',  
        'Keremeos',  
        'Oliver',  
        'Osoyoos',  
        'Penticton',  
        'Summerland',  
        'RegionalDistrictofCentralOkanagan',  
        'Peachland',  
        'WestKelowna',  
        'Kelowna',  
        'LakeCountry',  
        'RegionalDistrictofNorthOkanagan',  
        'Lumby',  
        'Coldstream',  
        'Vernon',  
        'Spallumcheen',  
        'Armstrong',  
        'Enderby',  
        'RegionalDistrictofCentralKootenay',  
        'Salmo',  
        'Creston',  
        'Wynndel/EastShoreKootenayLake',  
        'Nelson',  
        'LowerArrow/Columbia',  
        'Castlegar',  
        'TheSlocanValley',  
        'NewDenver',  
        'Silverton',  
        'Kaslo',  
        'TheArrowLakes',  
        'Nakusp',  
        'RegionalDistrictofEastKootenay',  
        'Fernie',  
        'Cranbrook',  
        'Kimberley',  
        'Sparwood',  
        'Elkford',  
        'CanalFlats',  
        'Invermere',  
        'RadiumHotSprings',  
        'ColumbiaShuswapRegionalDistrict',  
        'Golden',  
        'Revelstoke',  
        'Sicamous',  
        'SalmonArm',  
        'Thompson-NicolaRegionalDistrict',  
        'BeautifulNicolaValley-South',  
        'Merritt',  
        'BeautifulNicolaValley-North',  
        'BlueSkyCountry',  
        'Lytton',  
        'LoganLake',  
        'Ashcroft',  
        'CacheCreek',  
        'CopperDesertCountry',  
        'Grasslands',  
        'Kamloops',  
        'RiversandthePeaks',  
        'Chase',  
        'SunPeaksMountainResort',  
        'BonapartePlateau',  
        'Clinton',  
        'LowerNorthThompson',  
        'Barriere',  
        'ThompsonHeadwaters',  
        'Clearwater',  
        'WellsGrayCountry',  
        'CaribooRegionalDistrict',  
        '100MileHouse',  
        'WilliamsLake',  
        'Wells',  
        'Quesnel',  
        'RegionalDistrictofFraser-FortGeorge',  
        'Valemount',  
        'McBride',  
        'PrinceGeorge',  
        'Mackenzie',  
        'NorthCoastRegionalDistrict',  
        'DaajingGiids',  
        'PortClements',  
        'Masset',  
        'PortEdward',  
        'PrinceRupert',  
        'RegionalDistrictofKitimat-Stikine',  
        'Kitimat',  
        'Terrace',  
        'RegionalDistrictofBulkley-Nechako',  
        'FraserLake',  
        'Vanderhoof',  
        'FortStJames',  
        'BurnsLake',  
        'Houston',  
        'Smithers',  
        'Telkwa',  
        'Granisle',  
        'PeaceRiverRegionalDistrict',  
        'DawsonCreek',  
        'TumblerRidge',  
        'Chetwynd',  
        'HudsonsHope',  
        'Taylor',  
        'FortStJohn',  
        'CentralCoastRegionalDistrict',  
        'RegionalDistrictofKootenayBoundary',  
        'GrandForks',  
        'Greenwood',  
        'Midway',  
        'WestBoundary',  
        'RuralGrandForks',  
        'ChristinaLake',  
        'LowerColumbia/OldGlory',  
        'Rossland',  
        'Warfield',  
        'Trail',  
        'Montrose',  
        'Fruitvale',  
        'qathetRegionalDistrict',  
        'PowellRiver',  
        'NorthernRockiesRegionalMunicipality',  
        'StikineRegion(Unincorporated)',  
    ];           
//         
    const regions = [           
        {//Coastal BC           
            id: 'coastalBC',  zoom:[51.5, -127], size:6           
        },  
        {            id: 'CapitalRegionalDistrict',            zoom: [48.4331, -123.4527],             size: 10        },  
        {            id: 'SaltspringIsland',            zoom: [48.8202, -123.497],             size: 11        },  
        {            id: 'NorthSaanich',            zoom: [48.654, -123.434],             size: 13        },  
        {            id: 'Sidney',            zoom: [48.6539, -123.404],             size: 13        },  
        {            id: 'CentralSaanich',            zoom: [48.5864, -123.418],             size: 12        },  
        {            id: 'Saanich',            zoom: [48.5038, -123.385],             size: 12        },  
        {            id: 'Highlands',            zoom: [48.5179, -123.503],             size: 12        },  
        {            id: 'ViewRoyal',            zoom: [48.4698, -123.461],             size: 13        },  
        {            id: 'OakBay',            zoom: [48.4324, -123.306],             size: 13        },  
        {            id: 'Victoria',            zoom: [48.426, -123.355],             size: 13        },  
        {            id: 'Esquimalt',            zoom: [48.4327, -123.411],             size: 13        },  
        {            id: 'Colwood',            zoom: [48.4279, -123.482],             size: 13        },  
        {            id: 'Langford',            zoom: [48.449, -123.527],             size: 12        },  
        {            id: 'Metchosin',            zoom: [48.3684, -123.561],             size: 12        },  
        {            id: 'Sooke',            zoom: [48.4023, -123.692],             size: 12        },  
        {            id: 'CowichanValleyRegionalDistrict',            zoom: [48.7994, -124.1194],             size: 10        },  
        {            id: 'ShawniganLake',            zoom: [48.6619, -123.714],             size: 12        },  
        {            id: 'MillBay/Malahat',            zoom: [48.615, -123.53],             size: 12        },  
        {            id: 'CobbleHill',            zoom: [48.6998, -123.565],             size: 12        },  
        {            id: 'CowichanStation/Sahtlam/Glenora',            zoom: [48.7563, -123.77],             size: 12        },  
        {            id: 'CowichanBay',            zoom: [48.7484, -123.625],             size: 13        },  
        {            id: 'Duncan',            zoom: [48.7785, -123.701],             size: 14        },  
        {            id: 'NorthCowichan',            zoom: [48.8394, -123.679],             size: 12        },  
        {            id: 'LakeCowichan',            zoom: [48.8259, -124.052],             size: 12        },  
        {            id: 'Youbou/MeadeCreek',            zoom: [48.9429, -124.341],             size: 11        },  
        {            id: 'Ladysmith',            zoom: [48.9743, -123.801],             size: 12        },  
        {            id: 'NorthOyster/Diamond',            zoom: [49.0175, -123.861],             size: 13        },  
        {            id: 'RegionalDistrictofNanaimo',            zoom: [49.2048, -124.2499],             size: 10        },  
        {            id: 'Nanaimo',            zoom: [49.1754, -123.943],             size: 12        },  
        {            id: 'Lantzville',            zoom: [49.2306, -124.099],             size: 12        },  
        {            id: 'Parksville',            zoom: [49.3219, -124.318],             size: 12        },  
        {            id: 'QualicumBeach',            zoom: [49.3482, -124.431],             size: 12        },  
        {            id: 'ComoxValleyRegionalDistrict',            zoom: [49.655, -124.9915],             size: 10        },  
        {            id: 'BaynesSound-Denman/HornbyIslands',            zoom: [49.5428, -124.809],             size: 11        },  
        {            id: 'Cumberland',            zoom: [49.631, -125.042],             size: 11        },  
        {            id: 'Courtenay',            zoom: [49.6938, -124.986],             size: 12        },  
        {            id: 'Comox',            zoom: [49.6916, -124.909],             size: 12        },  
        {            id: 'Puntledge/BlackCreek',            zoom: [49.7555, -125.203],             size: 11        },  
        {            id: 'RegionalDistrictofAlberni-Clayoquot',            zoom: [49.221, -125.3375],             size: 10        },  
        {            id: 'PortAlberni',            zoom: [49.2485, -124.801],             size: 11        },  
        {            id: 'StrathconaRegionalDistrict',            zoom: [50.2057, -125.593],             size: 9        },  
        {            id: 'CampbellRiver',            zoom: [50.0001, -125.279],             size: 12        },  
        {            id: 'DiscoveryIslands/MainlandInlets',            zoom: [50.712, -124.962],             size: 10        },  
        {            id: 'Cortes',            zoom: [50.0982, -124.975],             size: 10        },  
        {            id: 'OysterBay/ButtleLake',            zoom: [49.8173, -125.546],             size: 10        },  
        {            id: 'Kyuquot/Nootka-Sayward',            zoom: [50.003, -125.973],             size: 10        },  
        {            id: 'GoldRiver',            zoom: [49.7353, -126.082],             size: 10        },  
        {            id: 'RegionalDistrictofMountWaddington',            zoom: [50.8898, -126.7493],             size: 9        },  
        {            id: 'PortMcNeill',            zoom: [50.5858, -127.102],             size: 10        },  
        {            id: 'AlertBay',            zoom: [50.5832, -126.919],             size: 11        },  
        {            id: 'PortHardy',            zoom: [50.6983, -127.424],             size: 10        },  
        {            id: 'PortAlice',            zoom: [50.4098, -127.481],             size: 10        },  
        {            id: 'MetroVancouverRegionalDistrict',            zoom: [49.2542, -122.9425],             size: 10        },  
        {            id: 'WhiteRock',            zoom: [49.0151, -122.817],             size: 12        },  
        {            id: 'Surrey',            zoom: [49.1078, -122.794],             size: 12        },  
        {            id: 'Langley',            zoom: [49.0943, -122.574],             size: 12        },  
        {            id: 'Delta',            zoom: [49.0775, -123.006],             size: 12        },  
        {            id: 'Richmond',            zoom: [49.1698, -123.16],             size: 12        },  
        {            id: 'Vancouver',            zoom: [49.2538, -123.114],             size: 12        },  
        {            id: 'Burnaby',            zoom: [49.2485, -122.965],             size: 12        },  
        {            id: 'NewWestminster',            zoom: [49.2086, -122.918],             size: 13        },  
        {            id: 'Coquitlam',            zoom: [49.2886, -122.784],             size: 13        },  
        {            id: 'PortMoody',            zoom: [49.2967, -122.876],             size: 13        },  
        {            id: 'Belcarra',            zoom: [49.3322, -122.905],             size: 13        },  
        {            id: 'Anmore',            zoom: [49.3462, -122.852],             size: 13        },  
        {            id: 'NorthVancouver',            zoom: [49.3605, -123.007],             size: 11        },  
        {            id: 'WestVancouver',            zoom: [49.3665, -123.2],             size: 12        },  
        {            id: 'PortCoquitlam',            zoom: [49.2534, -122.762],             size: 13        },  
        {            id: 'PittMeadows',            zoom: [49.2723, -122.665],             size: 12        },  
        {            id: 'MapleRidge',            zoom: [49.2627, -122.516],             size: 11        },  
        {            id: 'LionsBay',            zoom: [49.4622, -123.239],             size: 12        },  
        {            id: 'BowenIsland',            zoom: [49.3743, -123.372],             size: 11        },  
        {            id: 'SunshineCoastRegionalDistrict',            zoom: [49.7713, -123.7555],             size: 7        },  
        {            id: 'WestHoweSound',            zoom: [49.5003, -123.432],             size: 10        },  
        {            id: 'Gibsons',            zoom: [49.402, -123.513],             size: 10        },  
        {            id: 'Elphinstone',            zoom: [49.4194, -123.546],             size: 10        },  
        {            id: 'Sechelt',            zoom: [49.4715, -123.754],             size: 10        },  
        {            id: 'RobertsCreek',            zoom: [49.5057, -123.65],             size: 10        },  
        {            id: 'HalfmoonBay',            zoom: [49.6552, -123.7],             size: 10        },  
        {            id: 'Egmont/PenderHarbour',            zoom: [49.972, -123.861],             size: 10        },  
        {            id: 'Squamish-LillooetRegionalDistrict',            zoom: [50.5001, -122.9535],             size: 7        },  
        {            id: 'Squamish',            zoom: [49.7552, -123.138],             size: 10        },  
        {            id: 'Whistler',            zoom: [50.0908, -122.995],             size: 10        },  
        {            id: 'Pemberton',            zoom: [50.315, -122.812],             size: 10        },  
        {            id: 'Lillooet',            zoom: [50.6841, -121.912],             size: 10        },  
        {            id: 'FraserValleyRegionalDistrict',            zoom: [49.5508, -121.8713],             size: 7        },  
        {            id: 'Abbotsford',            zoom: [49.0701, -122.286],             size: 10        },  
        {            id: 'Mission',            zoom: [49.2363, -122.346],             size: 10        },  
        {            id: 'Chilliwack',            zoom: [49.142, -121.935],             size: 10        },  
        {            id: 'HarrisonHotSprings',            zoom: [49.2977, -121.784],             size: 10        },  
        {            id: 'Kent',            zoom: [49.2624, -121.76],             size: 10        },  
        {            id: 'Hope',            zoom: [49.379, -121.452],             size: 10        },  
        {            id: 'RegionalDistrictofOkanagan-Similkameen',            zoom: [49.4188, -120.1465],             size: 7        },  
        {            id: 'Princeton',            zoom: [49.3399, -120.525],             size: 10        },  
        {            id: 'Keremeos',            zoom: [49.2052, -119.825],             size: 10        },  
        {            id: 'Oliver',            zoom: [49.1836, -119.551],             size: 10        },  
        {            id: 'Osoyoos',            zoom: [49.0326, -119.468],             size: 10        },  
        {            id: 'Penticton',            zoom: [49.4925, -119.569],             size: 10        },  
        {            id: 'Summerland',            zoom: [49.6049, -119.679],             size: 10        },  
        {            id: 'RegionalDistrictofCentralOkanagan',            zoom: [49.9625, -119.4598],             size: 7        },  
        {            id: 'Peachland',            zoom: [49.7753, -119.741],             size: 10        },  
        {            id: 'WestKelowna',            zoom: [49.8402, -119.579],             size: 10        },  
        {            id: 'Kelowna',            zoom: [49.8858, -119.444],             size: 10        },  
        {            id: 'LakeCountry',            zoom: [50.077, -119.402],             size: 10        },  
        {            id: 'RegionalDistrictofNorthOkanagan',            zoom: [50.3812, -118.8226],             size: 7        },  
        {            id: 'Lumby',            zoom: [50.2496, -118.971],             size: 10        },  
        {            id: 'Coldstream',            zoom: [50.2281, -119.177],             size: 10        },  
        {            id: 'Vernon',            zoom: [50.2432, -119.323],             size: 10        },  
        {            id: 'Spallumcheen',            zoom: [50.412, -119.195],             size: 10        },  
        {            id: 'Armstrong',            zoom: [50.4461, -119.199],             size: 10        },  
        {            id: 'Enderby',            zoom: [50.5548, -119.144],             size: 10        },  
        {            id: 'RegionalDistrictofCentralKootenay',            zoom: [49.8953, -117.2516],             size: 7        },  
        {            id: 'Salmo',            zoom: [49.1916, -117.279],             size: 10        },  
        {            id: 'Creston',            zoom: [49.1076, -116.519],             size: 10        },  
        {            id: 'Wynndel/EastShoreKootenayLake',            zoom: [49.4369, -116.724],             size: 10        },  
        {            id: 'Nelson',            zoom: [49.494, -117.294],             size: 10        },  
        {            id: 'LowerArrow/Columbia',            zoom: [49.3828, -117.962],             size: 10        },  
        {            id: 'Castlegar',            zoom: [49.326, -117.66],             size: 10        },  
        {            id: 'TheSlocanValley',            zoom: [49.9095, -117.412],             size: 10        },  
        {            id: 'NewDenver',            zoom: [49.9936, -117.371],             size: 10        },  
        {            id: 'Silverton',            zoom: [49.9531, -117.359],             size: 10        },  
        {            id: 'Kaslo',            zoom: [49.911, -116.908],             size: 10        },  
        {            id: 'TheArrowLakes',            zoom: [50.1698, -117.986],             size: 10        },  
        {            id: 'Nakusp',            zoom: [50.2462, -117.807],             size: 10        },  
        {            id: 'RegionalDistrictofEastKootenay',            zoom: [49.9802, -115.5981],             size: 7        },  
        {            id: 'Fernie',            zoom: [49.504, -115.059],             size: 10        },  
        {            id: 'Cranbrook',            zoom: [49.5308, -115.759],             size: 10        },  
        {            id: 'Kimberley',            zoom: [49.667, -115.984],             size: 10        },  
        {            id: 'Sparwood',            zoom: [49.7361, -114.819],             size: 10        },  
        {            id: 'Elkford',            zoom: [50.04, -114.874],             size: 10        },  
        {            id: 'CanalFlats',            zoom: [50.1659, -115.821],             size: 10        },  
        {            id: 'Invermere',            zoom: [50.5017, -116.034],             size: 10        },  
        {            id: 'RadiumHotSprings',            zoom: [50.6267, -116.08],             size: 10        },  
        {            id: 'ColumbiaShuswapRegionalDistrict',            zoom: [51.3964, -117.9492],             size: 7        },  
        {            id: 'Golden',            zoom: [51.3005, -116.961],             size: 10        },  
        {            id: 'Revelstoke',            zoom: [50.9968, -118.193],             size: 10        },  
        {            id: 'Sicamous',            zoom: [50.8375, -118.98],             size: 10        },  
        {            id: 'SalmonArm',            zoom: [50.7029, -119.287],             size: 10        },  
        {            id: 'Thompson-NicolaRegionalDistrict',            zoom: [51.049, -120.4047],             size: 7        },  
        {            id: 'BeautifulNicolaValley-South',            zoom: [49.9441, -120.931],             size: 10        },  
        {            id: 'Merritt',            zoom: [50.113, -120.774],             size: 10        },  
        {            id: 'BeautifulNicolaValley-North',            zoom: [50.1612, -120.313],             size: 10        },  
        {            id: 'BlueSkyCountry',            zoom: [50.4568, -121.494],             size: 10        },  
        {            id: 'Lytton',            zoom: [50.228, -121.568],             size: 10        },  
        {            id: 'LoganLake',            zoom: [50.4848, -121.017],             size: 10        },  
        {            id: 'Ashcroft',            zoom: [50.6955, -121.338],             size: 10        },  
        {            id: 'CacheCreek',            zoom: [50.7983, -121.318],             size: 10        },  
        {            id: 'CopperDesertCountry',            zoom: [50.8174, -120.715],             size: 10        },  
        {            id: 'Grasslands',            zoom: [50.5057, -119.92],             size: 10        },  
        {            id: 'Kamloops',            zoom: [50.6766, -120.347],             size: 10        },  
        {            id: 'RiversandthePeaks',            zoom: [50.8386, -120.102],             size: 10        },  
        {            id: 'Chase',            zoom: [50.8224, -119.686],             size: 10        },  
        {            id: 'SunPeaksMountainResort',            zoom: [50.8911, -119.899],             size: 10        },  
        {            id: 'BonapartePlateau',            zoom: [51.2653, -121.564],             size: 10        },  
        {            id: 'Clinton',            zoom: [51.0929, -121.58],             size: 10        },  
        {            id: 'LowerNorthThompson',            zoom: [51.2605, -119.827],             size: 10        },  
        {            id: 'Barriere',            zoom: [51.176, -120.127],             size: 10        },  
        {            id: 'ThompsonHeadwaters',            zoom: [52.1291, -119.285],             size: 10        },  
        {            id: 'Clearwater',            zoom: [51.6528, -120.035],             size: 10        },  
        {            id: 'WellsGrayCountry',            zoom: [52.1527, -120.002],             size: 10        },  
        {            id: 'CaribooRegionalDistrict',            zoom: [52.3494, -123.1512],             size: 7        },  
        {            id: '100MileHouse',            zoom: [51.6439, -121.308],             size: 10        },  
        {            id: 'WilliamsLake',            zoom: [52.1289, -122.139],             size: 10        },  
        {            id: 'Wells',            zoom: [53.1081, -121.626],             size: 10        },  
        {            id: 'Quesnel',            zoom: [52.9904, -122.477],             size: 10        },  
        {            id: 'RegionalDistrictofFraser-FortGeorge',            zoom: [53.9632, -121.5143],             size: 7        },  
        {            id: 'Valemount',            zoom: [52.8303, -119.267],             size: 10        },  
        {            id: 'McBride',            zoom: [53.3066, -120.165],             size: 10        },  
        {            id: 'PrinceGeorge',            zoom: [53.9289, -122.761],             size: 10        },  
        {            id: 'Mackenzie',            zoom: [55.3138, -123.152],             size: 10        },  
        {            id: 'NorthCoastRegionalDistrict',            zoom: [53.3381, -131.0504],             size: 7        },  
        {            id: 'DaajingGiids',            zoom: [53.2514, -132.087],             size: 10        },  
        {            id: 'PortClements',            zoom: [53.69, -132.174],             size: 10        },  
        {            id: 'Masset',            zoom: [54.0166, -132.115],             size: 10        },  
        {            id: 'PortEdward',            zoom: [54.2123, -130.121],             size: 10        },  
        {            id: 'PrinceRupert',            zoom: [54.285, -130.298],             size: 10        },  
        {            id: 'RegionalDistrictofKitimat-Stikine',            zoom: [56.0235, -129.2596],             size: 7        },  
        {            id: 'Kitimat',            zoom: [54.0159, -128.673],             size: 10        },  
        {            id: 'Terrace',            zoom: [54.4737, -128.574],             size: 10        },  
        {            id: 'RegionalDistrictofBulkley-Nechako',            zoom: [54.5727, -125.5353],             size: 7        },  
        {            id: 'FraserLake',            zoom: [54.0602, -124.849],             size: 10        },  
        {            id: 'Vanderhoof',            zoom: [54.0179, -124.013],             size: 10        },  
        {            id: 'FortStJames',            zoom: [54.4761, -124.22],             size: 10        },  
        {            id: 'BurnsLake',            zoom: [54.2231, -125.739],             size: 10        },  
        {            id: 'Houston',            zoom: [54.3958, -126.664],             size: 10        },  
        {            id: 'Smithers',            zoom: [54.78, -127.165],             size: 10        },  
        {            id: 'Telkwa',            zoom: [54.6861, -127.056],             size: 10        },  
        {            id: 'Granisle',            zoom: [54.9545, -126.195],             size: 10        },  
        {            id: 'PeaceRiverRegionalDistrict',            zoom: [56.8255, -122.0636],             size: 7        },  
        {            id: 'DawsonCreek',            zoom: [55.7528, -120.232],             size: 10        },  
        {            id: 'TumblerRidge',            zoom: [55.0668, -121.1416],             size: 10        },  
        {            id: 'Chetwynd',            zoom: [55.7235, -121.6387],             size: 10        },  
        {            id: 'HudsonsHope',            zoom: [56.024, -122.0205],             size: 10        },  
        {            id: 'Taylor',            zoom: [56.1557, -120.6816],             size: 10        },  
        {            id: 'FortStJohn',            zoom: [56.2459, -120.834],             size: 10        },  
        {            id: 'CentralCoastRegionalDistrict',            zoom: [52.0325, -127.2473],             size: 7        },  
        {            id: 'RegionalDistrictofKootenayBoundary',            zoom: [49.3571, -118.4134],             size: 7        },  
        {            id: 'GrandForks',            zoom: [49.031, -118.441],             size: 10        },  
        {            id: 'Greenwood',            zoom: [49.0935, -118.6783],             size: 10        },  
        {            id: 'Midway',            zoom: [49.0087, -118.7987],             size: 10        },  
        {            id: 'WestBoundary',            zoom: [49.4146, -118.9493],             size: 10        },  
        {            id: 'RuralGrandForks',            zoom: [49.4096, -118.4536],             size: 10        },  
        {            id: 'ChristinaLake',            zoom: [49.135, -118.2119],             size: 10        },  
        {            id: 'LowerColumbia/OldGlory',            zoom: [49.1323, -117.9757],             size: 10        },  
        {            id: 'Rossland',            zoom: [49.1206, -117.8462],             size: 10        },  
        {            id: 'Warfield',            zoom: [49.0948, -117.7485],             size: 10        },  
        {            id: 'Trail',            zoom: [49.1024, -117.6857],             size: 10        },  
        {            id: 'Montrose',            zoom: [49.0786, -117.5904],             size: 10        },  
        {            id: 'Fruitvale',            zoom: [49.1103, -117.5496],             size: 10        },  
        {            id: 'qathetRegionalDistrict',            zoom: [50.1433, -124.3982],             size: 7        },  
        {            id: 'PowellRiver',            zoom: [49.8745, -124.552],             size: 10        },  
        {            id: 'NorthernRockiesRegionalMunicipality',            zoom: [58.9909, -123.0798],             size: 7        },  
        {            id: 'StikineRegion(Unincorporated)',            zoom: [59.0164, -131.77],             size: 7        },  
    ];           
